name: cnp_romania_parser
description: A parser for C.N.P. (short for Cod Numeric Personal or Personal Identification Number).
version: 0.0.1
repository: https://github.com/pleshkov-i-v/cnp_romania_parser
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
# dependencies:

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
